/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'szimano' at '1/10/15 3:40 PM' with Gradle 2.0
 *
 * @author szimano, @date 1/10/15 3:40 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "main can be initiated"() {
        setup:
        Main main = new Main()
        when:
        def result = main
        then:
        result != null
    }
}
