/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'szimano' at '1/10/15 3:40 PM' with Gradle 2.0
 *
 * @author szimano, @date 1/10/15 3:40 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
