/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'szimano' at '1/10/15 3:40 PM' with Gradle 2.0
 *
 * @author szimano, @date 1/10/15 3:40 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
